### PR TITLE
Fix NPS Summary curl request example

### PR DESCRIPTION
**Pull request by diegoserranoa**
Other changes:
-Remove unused file

### CODE REVIEW

**Comment by marinhero** [comment]
By following the example using dates I get the following error:

```marin@~$> curl -H "Authorization: Bearer 7bb3bebfddbaa13808bdbb7b3dec0ede81473167799825eadff99374a56f1268" "https://api.wootric.com/v1/nps_summary?date[start]='2016-01-01'&date[end]='2017-01-01'"
curl: (3) [globbing] bad range in column 45```

Did I missed anything?

**Comment by diegoserranoa** [comment]
Mmm I guess it depends on the terminal. You need to escape `\[start\]` and `\[end\]`, or use `--globoff`
Should I include that?

**Comment by marinhero** [comment]
Ok, now it works, shall we use the encoded version instead? 
```
curl -H "Authorization: Bearer 7bb3bebfddbaa13808bdbb7b3dec0ede81473167799825eadff99374a56f1268" "https://api.wootric.com/v1/nps_summary?date%5Bstart%5B='2016-01-01'&date%5Bend%5D='2017-01-01'"```

**Comment by diegoserranoa** [comment]
I'll do that. Thanks @marinhero

**Comment by diegoserranoa** [comment]
Done! @marinhero

**Pull request merged**
