### PR TITLE
Add Bulgarian language

### PR DESCRIPTION
**Pull request by ambarwootric**
Doc: https://docs.google.com/spreadsheets/d/1JsDd4WKwuyFwvIcXXtA-4LpvuO4dlnRceHyqqMhM-Y4/edit#gid=0

Trello: https://trello.com/c/NbsRF8Bg/2113-add-bulgarian-language-to-all-surveys

### CODE REVIEW

**Review by marinhero — CHANGES_REQUESTED** [review]
According to https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
the language code for Bulgarian is `bg` and not `bl` 
Are you following any convention? if so please provide a link else change the language code

**Comment by ambarwootric** [comment]
To truly speaking I didn't knew that we were using conventions and thought that names/codes are given by ourselves. Ok I will update the PR's.

**Comment by marinhero** [comment]
No worries Ambar. There's not a written rule about it. It's just nice to be able to find a language easily by following a convention. Let me know when I can take another look.

**Comment by ambarwootric** [comment]
Thanks Marin, you can now take another look.

**Review by marinhero — APPROVED** [review]
Thanks! Go ahead and merge it in!

**Pull request merged**
