### PR TITLE
Update delete end_user documentation

### PR DESCRIPTION
**Pull request by gmonfort**
Update delete end_user documentation

## Changes
- Clearly state that when deleting end_users using the API, the deletion
  process will be *scheduled* the next day (instead of performed)

## JIRA story
https://jira.inmoment.com/browse/DEV-20985

## JIRA Code Review / QA subtask
https://jira.inmoment.com/browse/DEV-21022

### CODE REVIEW

**Review by jessekathryn — COMMENTED** [review]
🚀

**Review by jessekathryn — APPROVED** [review]
LGTM!

**Comment by jessekathryn** [comment]
Screen Shot 2022-03-24 at 12 39 24 PM

**Comment by gmonfort** [comment]
Thanks @jessekathryn

**Pull request merged**
