### PR TITLE
Add Ukrainian language

### PR DESCRIPTION
**Pull request by ambarwootric**
Doc: https://docs.google.com/spreadsheets/d/1f_mDMga5y7vKznpYZ3mFzDgzXashoBnagchxtID6F_w/edit#gid=0

Trello: https://trello.com/c/Iecy2SO6/2466-customer-request-to-add-ukrainian-3067-transfergo-they-are-enteprise-lite-and-did-the-translation-https-docsgooglecom-spreadshee

Note: Note: This PR works with another PR from wootric https://github.com/Wootric/wootric/pull/1897 and survey https://github.com/Wootric/survey/pull/198

### CODE REVIEW

**Review by marinhero — COMMENTED** [review]
According to https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes Ukrainian language code is `UK` are you using other standard ?

**Comment by ambarwootric** [comment]
I was aware of a naming convention this time but looks like instead of language-specific code provided I somehow went for country code http://www.nationsonline.org/oneworld/country_code_list.htm. As I on many references found `UA` so chosen it. Ok, I will update it `UK` and will keep in mind to choose from above reference from further on. Thank You!

**Comment by marinhero** [comment]
Ahh makes sense! Let's keep to language code  👍

**Review by marinhero — APPROVED** [review]
Bien :shipit:

**Pull request merged**
