### PR TITLE
Update logo

### PR DESCRIPTION
**Pull request by egollas**

### CODE REVIEW

**Review by diegoserranoa — CHANGES_REQUESTED** [review]
I *think* the logo needs some resizing/fixing. Code looks good so I'll let @DanPitrowiski do all the design calls. 👍  

Screen Shot 2021-06-24 at 12 16 33 PM

**Comment by DanPitrowiski** [comment]
> I _think_ the logo needs some resizing/fixing. Code looks good so I'll let @DanPitrowiski do all the design calls. 👍
> 

Yeah @egollas - I see what the problem is in the CSS. 

```
.wootric-doc-topbar__logo a {
    background-image: url(../images/wootric-docs_logo.png);
    background-repeat: no-repeat;
    background-size: cover;
    display: block;
    height: 40px;
    width: 330px;
}
```

To make it easier for everyone here is a logo that is exactly @2x the size of what the CSS wants. It should fit and not cut off anything.

developer-wootric-is-now-inmoment

**Comment by egollas** [comment]
@dankorzeniewski , I've updated the logo.
Please check again.

**Comment by DanPitrowiski** [comment]
@egollas I'm not sure how to view the https://docs.wootric.com/ page just from the PR. Could you just post a screenshot? That should be enough to know if the logo fits.

**Comment by egollas** [comment]
@DanPitrowiski , I am fixing some local environment issue. I will send screenshot after fix.

**Comment by egollas** [comment]
@DanPitrowiski Here's the screenshot.
Please let me know if it looks good.
image

**Comment by DanPitrowiski** [comment]
Yes this looks great @egollas :+1: - looks ready for production.

**Review by diegoserranoa — APPROVED** [review]
Approving since @DanPitrowiski gave the 👍 

:shipit:

**Pull request merged**
